language: node_js
node_js:
    - "10"
    - "12"
os:
    - linux
    - osx

# Leaving the exclusion here for quick reference if exclusions are needed in the future.
# matrix:
#     exclude:
#         - os: osx # skip this because on Travis, node.js segfaults on osx+node 11
#           node_js: "11"
